on: [push]
branches:
  - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: Azure/docker-login@v1
        with:
          login-server: miyashita.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t miyashita.azurecr.io/todo:${{ github.sha }}
          docker push miyashita.azurecr.io/todo:${{ github.sha }}

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: miyashita
          resource-group: todo

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: miyashita.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: todo-secret

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            todo.yml
          images: |
            miyashita.azurecr.io/todo:${{ github.sha }}
          imagepullsecrets: |
            todo-secret
